name: Build MCLauncher

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore MCLauncher.sln

      - name: Build solution (Release, x64)
        run: msbuild MCLauncher.sln /p:Configuration=Release /p:Platform=x64

      - name: Create ZIP package
        run: |
          mkdir output
          Copy-Item -Path "x64/Release/*" -Destination "output" -Recurse
          Compress-Archive -Path output/* -DestinationPath MCLauncher.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MCLauncher
          path: MCLauncher.zip
